### PR TITLE
SL-2103 update jsf to stoplightio/json-schema-faker fork

### PR DESCRIPTION
**Pull request by pytlesk4**
- setup jsf with sane defaults

### CODE REVIEW

**Comment by philsturgeon** [comment]
Do you have a JIRA issue to help us track getting rid of the fork? If you could comment it in here I'll approve this great change.

**Comment by pytlesk4** [comment]
https://stoplightio.atlassian.net/browse/SL-2103

**Comment by philsturgeon** [comment]
@pytlesk4 thanks tom, but this is the JIRA issue for this work. I meant the JIRA issue for removing our fork of json-schema-faker, merging the changes back upstream, and switching back to using the main version. If we dont yet have a JIRA issue for this could you make one? We have a lot forks of things and we cannot possibly maintain them all.

**Comment by pytlesk4** [comment]
There is not a JIRA issue, I will make one, and then try to get them merged back up stream. We will need to keep our fork around until the changes get released in the upstream repo.

**Comment by pytlesk4** [comment]
@philsturgeon https://stoplightio.atlassian.net/browse/SL-2135

**Pull request merged**
