### PR TITLE
Scratch docker image and automatic build by circleci

### PR DESCRIPTION
**Pull request by KillianH**
## Checklist

- [ ] Tests have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Tagging strategy

_As of right now there's no proper tagging strategy. There's just the branch name for the build tag_

## What kind of change does this PR introduce?

_Feature : Automatic build of a scratch image based on binaries generated on circleci_

## What is the current behavior? What is the new behavior?

_⚠️  https://github.com/stoplightio/prism/issues/375 ⚠️ We need to fix this before merging I think._
_33mb image 🎊_
_I don't really know if the dockerfile is correct actually. I've tried to generate an alpine binary with pkg but I was having some weird issue like some libgc dependency missing on my alpine container._
_I've used a cool hack from @martinandert https://gist.github.com/bcardiff/85ae47e66ff0df35a78697508fcb49af_

## Does this PR introduce a breaking change?

_⚠️ CI/CD breaking change. ⚠️ You need to add your docker credentials to your circleci project env variables_

### CODE REVIEW

**Comment by KillianH** [comment]
Hmm I'm still new with circleci but is it normal that the checks runs on my circleci project ? 😕

**Comment by KillianH** [comment]
Another problem with the scratch image : the cli don't work with URL
`[CLI] ✖  fatal     getaddrinfo ENOTFOUND raw.githack.com raw.githack.com:443`

**Comment by XVincentX** [comment]
> Hmm I'm still new with circleci but is it normal that the checks runs on my circleci project ?

This is most likely because we have configured CircleCI to not propagate our environment variables in foreign builds — therefore you'll get kicked out from the authentication of the various services we use.

For the second part — I've already set up an automation from DockerHub directly. Every time something goes in master a new `stoplight/prism:master` image is generated and every time a tag is released you'll get a `stoplight/prism:3` and `stoplight/prism:3.x` tagged images as well, therefore I do not think we're going to need this.

---

Binary images could be fine, however I'd rather stay on the node one since I do not trust `pkg` entirely (yet)

Does this answer all your questions? Feel free to reopen if your aim was different.

**Comment by KillianH** [comment]
Oh ok no problem :) I was thinking that you would like a CI automation from the Devops/Docker PR recently. And I misreaden your comment : 

> Shall we ship the Docker image with the binaries we produce, or use a node based image? My gut says we should go with the **latter**.

That's why. However thank you for your comments ! :)

**Comment by XVincentX** [comment]
I take the blame here, I haven't been clear on some points and changed idea on other ones — let's stay simple for now and we'll go with binaries in case it's really required.

I apologize!

**Comment by KillianH** [comment]
No worry it was fun to do :smile:

**Pull request closed without merging**
