### PR TITLE
refactor: kill forwarder

### PR DESCRIPTION
**Pull request by XVincentX**
The forwarder concept is something that has never been used and needs to be redesigned. Per @philsturgeon request we're going to remove the whole concept and redesign it from scratch as a real proxy server when we'll hit the good time.

I haven't removed some of the related tests so I can re-enable them once the proxy feature will be back.

### CODE REVIEW

**Comment by XVincentX** [comment]
BOOM

**Comment by lag-of-death** [comment]
@XVincentX, I don't think we are to implement a real proxy server - https://github.com/stoplightio/prism/issues/473#issuecomment-533165658 The forwarder might have been useful for that

**Comment by philsturgeon** [comment]
@lag-of-death I'm not sure what a "real" proxy means to you, but when a customer makes a request to prism it will make a request to an upstream server. That's a proxy :)

Some of this code might have been useful, but the name was confusing, and the code was confusing. It was all smushed in with mocking and the options and implementation had to go so we can plan a good solution from scratch. Designing a new thing when you have an old thing around always taints the new design to match the old design, and we don't want that. We want to build this code from scratch, to have no confusion with mocking. :)

**Comment by lag-of-death** [comment]
thanks @philsturgeon, I responded in https://github.com/stoplightio/prism/issues/473#issuecomment-533194802 I'm thankful for clearing up the confusion :+1:

**Pull request merged**
