### PR TITLE
Updating documentation for proxy mode with docker

### PR DESCRIPTION
**Pull request by frangarcia**

### CODE REVIEW

**Comment by XVincentX** [comment]
@frangarcia I would say there are more idiomatic ways.

When running a docker container, you can reach the host with the special DNS name `host.docker.internal` on Mac (and recently Linux as well).

You can always do the same in other OS'es using the `--add-host` as you described or find other workarounds if required.

https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

Would you mind updating the PR with this new informations?

P.S: Soy de Madrid — me he mudado en Austin hace poco, y ya hecho de menos España!

**Comment by frangarcia** [comment]
Thanks! I didn't know that way of reaching out the host from a docker container. 

Disfruta Austin!

**Comment by frangarcia** [comment]
Is there anything else to do to see those changes in the docs at https://stoplight.io/p/docs/gh/stoplightio/prism/docs/getting-started/01-installation.md?srn=gh/stoplightio/prism/docs/getting-started/01-installation.md ?

**Comment by XVincentX** [comment]
@frangarcia Simplemente tenemos que lanzar el proceso de publicación. Yo me encargo de esto.

**Pull request merged**
