### PR TITLE
Unexpected throw

### PR DESCRIPTION
**Pull request by nulltoken**
@XVincentX At $DAYJOB, we've started to use Prism as a shadow experiment in order to perform validation of requests/responses. We log and compare inputs/outputs of the current validation implementation we're using against a Prism powered one.

This PR puts under the light a corner case usage of Prism that makes the lib crash.

I understand the use case looks weird and I apologize about it. Indeed, this doesn't provide a lot of context to work with. But this is all what we've got to work with as well on our side.

This is the simplest repro case I've been able to produce.

### CODE REVIEW

**Comment by XVincentX** [comment]
@nulltoken I think there's a file missing in this PR. Can you check it out?

**Comment by nulltoken** [comment]
> @nulltoken I think there's a file missing in this PR. Can you check it out?

Sorry. I pushed a little to early while I was uncrufting the repro case. Should be fixed now.

**Comment by nulltoken** [comment]
@XVincentX The CI failure is consistent with what I'm seeing at $DAYJOB:

```
    Error name:    "TypeError"
    Error message: "target.split is not a function"

          42 | 
          43 | export function splitUriParams(target: string) {
        > 44 |   return target.split('&').reduce((result: Dictionary<string>, pair: string) => {
             |                 ^
          45 |     const [key, ...rest] = pair.split('=');
          46 |     result[key] = rest.join('=');
          47 |     return result;

          at splitUriParams (packages/http/src/validator/validators/body.ts:44:17)
          at deserializeAndValidate (packages/http/src/validator/validators/body.ts:69:28)
          at packages/http/src/validator/validators/body.ts:116:26
          at node_modules/fp-ts/lib/Option.js:87:60
          at Object.pipe (node_modules/fp-ts/lib/pipeable.js:13:23)
          at packages/http/src/validator/validators/body.ts:106:11
          at node_modules/fp-ts/lib/Option.js:87:60
          at Object.pipe (node_modules/fp-ts/lib/pipeable.js:9:20)
          at HttpBodyValidator.validate (packages/http/src/validator/validators/body.ts:101:12)
          at packages/http/src/validator/index.ts:51:43
```

**Comment by XVincentX** [comment]
@nulltoken How did you end up with such input? This is something that shall never happen in Prism. Do you have a reproducible curl command I can use to get in such situation?

Basically what's happened here is that you claim that the content is formdata, but the body property has been parsed, which means it's JSON Compatible. As far as I remember, there is no way you can get in such situation in Prism.

**Comment by XVincentX** [comment]
Please reopen when you have more informations.

**Pull request closed without merging**
