### PR TITLE
[SO-194] Prism (v3) : Integration tests for ?__example=examplename

### PR DESCRIPTION
**Pull request by lag-of-death**
## Checklist

- ~[ ] Tests have been added (for bug fixes / features)~
- ~[ ] Docs have been added / updated (for bug fixes / features)~

## What kind of change does this PR introduce

Adding tests for an already existing functionality.

## What is the current behavior

No change in the functionality itself.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Agree with @XVincentX we want to show example selection is doing its thing, we should also have a third test which shows what happens when an invalid example is requested.

Does it error or just ignore it and pretend you didn’t even request an example?

**Comment by XVincentX** [comment]
You should receive an error message if the example you're selecting is not existing.

**Comment by lag-of-death** [comment]
@phil, @XVincentX, I think that the concerns are addressed now. Can one of you approve if OK?

**Comment by philsturgeon** [comment]
Nicely done, merge away!

**Pull request merged**
