### PR TITLE
Minor matchPath fixes

### PR DESCRIPTION
**Pull request by nulltoken**
**Summary**

Some quick fixes to `matchPath` and related tests:
 - Drop code related to special casing the column character (`:`). It's no longer needed.
   - Incidentally this fixes a bug where `/part/ab:17/process` wasn't considered a valid match for `/part/{something}/process`
 - Fix a code regression that was show casing as a flaky test
   - Created a specific test case to isolate (and fix) the regression. The issue wasn't caught by CI builds, because most of the dynamically generated test cases were statistically comparing against **partially** templated paths (eg `/a/b/c` vs `/{d}/e/{f}/g`).
 - Added a guard to ensure processed paths always start with a leading slash
   - Fixed a related test that was passing for the wrong reason

**Checklist**

- The basics
  - [x] I tested these changes manually in my local or dev environment
- Tests
  - [x] Added or updated
  - [ ] N/A
- Event Tracking
  - [ ] I added event tracking and followed the event tracking guidelines
  - [x] N/A
- Error Reporting
  - [ ] I reported errors and followed the error reporting guidelines
  - [x] N/A

/cc @chohmann

### CODE REVIEW

**Comment by nulltoken** [comment]
@radzserg @chohmann When do you think you might be able to peek at this PR please?

Indeed, although the PR title is relatively low key, this proposal _actually_ fixes an issue we're suffering from (`/part/ab:17/process` no being considered a valid match for `/part/{something}/process` because of the way columns are special cased).

**Comment by radzserg** [comment]
I'll review today or tomorrow.

**Review by radzserg — APPROVED** [review]
Nicely done 👍

**Comment by nulltoken** [comment]
@radzserg Thanks for the review, Sir! :heart:

**Pull request merged**
