### PR TITLE
fix: pin @stoplight/json dep to 3.20.0

### PR DESCRIPTION
**Pull request by yjp20**
Addresses #2566

**Checklist**

- The basics
  - [x] I tested these changes manually in my local or dev environment
- Tests
  - [ ] Added or updated
  - [x] N/A
- Event Tracking
  - [ ] I added event tracking and followed the event tracking guidelines
  - [x] N/A
- Error Reporting
  - [ ] I reported errors and followed the error reporting guidelines
  - [x] N/A

### CODE REVIEW

**Comment by rattrayalex** [comment]
cc @chohmann – any chance you could give this a quick stamp? the bad dep causes things to be Very Broken.

**Comment by RobertCraigie** [comment]
cc @mnaumanali94 can anyone take a look at this? it's breaking everything for us

**Review by mnaumanali94 — APPROVED** [review]

**Comment by mnaumanali94** [comment]
@RobertCraigie The team should be able to look at this tomorrow.  We're in a bit of a transition in terms of ownership  - we apologize for the wait.

**Comment by rattrayalex** [comment]
@mnaumanali94 anything we could do to persuade you to go ahead and release this? It's just a dependency pin to a previous-known-good version, and the breakage is quite bad (for us at least, and it seems, others too).

**Comment by mnaumanali94** [comment]
@rattrayalex This issue should be fixed now as a new version of stoplight/json should fix the error. Can y'all confirm please?

**Comment by rattrayalex** [comment]
Amazing, thank you @mnaumanali94 ! We'll give it a try shortly!

**Comment by RobertCraigie** [comment]
It looks like it's [still failing](https://github.com/openai/openai-python/actions/runs/10043944820/job/27823299663) but I haven't verified if this CI run is using the new stoplight/json version or not.

We've published a fork of `prism-cli` with the fix in this PR which is passing all our tests.

**Comment by mnaumanali94** [comment]
Is there a reason you are reverting to 3.20.0 and not 3.21.0?

**Comment by mnaumanali94** [comment]
Also trying on the command line with the steps to reproduce It doesn't fail. Can you see if the CI is using the right version?

**Comment by RobertCraigie** [comment]
@mnaumanali94 see this [CI run](https://github.com/openai/openai-python/actions/runs/10390556902/job/28771296332) which includes a debug log showing the versions of all deps.

It's using `@stoplight/json@3.21.6` and failing.

**Comment by Didel** [comment]
Resolves #2578

**Comment by lukaszzazulak** [comment]
@yjp20 sorry for the delay, could you resolve conflicts?

**Review by lukaszzazulak — COMMENTED** [review]
@yjp20 sorry for the delay, could you resolve conflicts?

**Pull request closed without merging**
