### PR TITLE
fix: readOnly objects in arrays are handled correctly

### PR DESCRIPTION
**Pull request by ilanashapiro**
Addresses #2336

**Summary**

Currently, given an object with a readOnly required field, Prism does not handle it properly as soon as the object is embedded into an array. Specifically, the user will get an error saying they must manually specify the readOnly property. This PR fixes this issue for all possibilities of arrays: single-typed arrays specified by a single item schema, and tuple-typed arrays specified by a list of item schemas, both with and without the additionalItems schema for tuple-typed arrays.

See: https://json-schema.org/understanding-json-schema/reference/array 
And also see: https://tools.ietf.org/html/draft-zyp-json-schema-03 for items type signature (sections 5.5, 6.4, and 6.9) and additionalItems type signature (sections 5.6, 6.4, and 6.10) in the code

**Checklist**

- The basics
  - [X] I tested these changes manually in my local or dev environment
- Tests
  - [X] Added or updated
  - [ ] N/A
- Event Tracking
  - [ ] I added event tracking and followed the event tracking guidelines
  - [X] N/A
- Error Reporting
  - [ ] I reported errors and followed the error reporting guidelines
  - [X] N/A

**Screenshots**
**--------------------------------------------------READONLY TESTS--------------------------------------------------**
Given the following schema (which includes a non-tuple-typed array):
```
openapi: 3.1.0

paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Pets'
      responses:
        '200':
          description: A pet id
          "content":
            application/json:
              schema:
                type: object
                properties:
                  id:     
                    type: integer
                    format: int64
                required: 
                  - "id"
                additionalProperties: false

  
components:
  schemas:
    Pets:
      type: object
      properties:
        objectsArray:
          type: array
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                readOnly: true
                type: string
              name:
                type: string
        title:
          type: string
          readOnly: true
        address:
          type: integer
      required:
        - title
        - address
```

I send the following POST request successfully:
image
image

With Prism before this fix, we get an error:
image
image

If I change the schema to include a tuple-typed array, with additionalItems specified for demonstration like so:
```
openapi: 3.1.0

paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Pets'
      responses:
        '200':
          description: A pet id
          "content":
            application/json:
              schema:
                type: object
                properties:
                  id:     
                    type: integer
                    format: int64
                required: 
                  - "id"
                additionalProperties: false

  
components:
  schemas:
    Pets:
      type: object
      properties:
        objectsArrayWithAdditionalItems:
          type: array
          items:
            - type: object
              required:
                - id
                - name
              properties:
                id:
                  readOnly: true
                  type: string
                name:
                  type: string
            - type: object
              required:
                - address
                - title
              properties:
                address:
                  readOnly: true
                  type: string
                title:
                  type: string
          additionalItems:
            type: object
            required:
              - status
              - ticket
            properties:
              status:
                readOnly: true
                type: string
              ticket:
                type: string
```
 
we see that the fix  works for readonly properties in both the tuple-typed items list, and the additionalItems schema object.
image
image

With Prism before this fix, we get an error:
image
image

**--------------------------------------------------WRITEONLY TESTS--------------------------------------------------**
Given the following schema (which includes a non-tuple-typed array):
```
openapi: 3.1.0

paths:
  /pets:
    get:
      requestBody: {}
      responses:
        '200':
          description: Detailed pet information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'

components:
  schemas:
    Pets:
      type: object
      properties:
        objectsArray:
          type: array
          items:
            type: object
            required:
              - id
              - name
            properties:
              id:
                writeOnly: true
                type: string
              name:
                type: string
              additionalItems: false
        title:
          type: string
          writeOnly: true
        address:
          type: integer
        additionalItems: false
      required:
        - title
        - address
```

I send the following POST request and get a response with the writeOnly properties (including the "id" property in the array) excluded as they're supposed to be:
image
image

With Prism before this fix, we get the writeOnly property "id" from the array inappropriately included in the response:
image
image

If I change the schema to include a tuple-typed array:
```
openapi: 3.1.0

paths:
  /pets:
    get:
      requestBody: {}
      responses:
        '200':
          description: Detailed pet information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'

components:
  schemas:
    Pets:
      type: object
      properties:
        objectsArrayWithAdditionalItems:
          type: array
          items:
            - type: object
              required:
                - id
                - name
              properties:
                id:
                  writeOnly: true
                  type: string
                name:
                  type: string
                additionalProperties: false
            - type: object
              required:
                - address
                - title
              properties:
                address:
                  writeOnly: true
                  type: string
                title:
                  type: string
                additionalProperties: false
        additionalProperties: false
```

we see that the fix works for writeOnly properties in the tuple-typed array -- they're appropriately excluded from the response:
image
image

With Prism before this fix, however, the writeOnly properties in the array are inappropriately returned in the response:
image
image

### CODE REVIEW

**Comment by ilanashapiro** [comment]
@rattrayalex

**Comment by brendarearden** [comment]
Thank you for opening this PR! Everything here looks great. After reviewing, we are wondering if these array changes need to be added for `writeOnly` as well. Is that something you would be willing to add as part of this PR?

**Comment by ilanashapiro** [comment]
Hi Brenda, thanks for the feedback! I thought about this for a moment and realized that the existing PR actually does handle arrays with ```writeOnly``` as well (it's independent of the predicate used). I am working on adding some test cases for this and will update shortly!

**Comment by ilanashapiro** [comment]
I've added tests (unit and end-end) showing this works for writeonly. However, I didn't include additionalItems in the tuple typed array for the end-end tests. additionalItems are indeed being filtered correctly for both readOnly and writeOnly based on the unit tests, but there is apparently an unrelated bug in Prism where additionalItems are never returned in the response. See the following repro using the master branch of Prism:
```
openapi: 3.1.0

paths:
  /pets:
    get:
      requestBody: {}
      responses:
        '200':
          description: Detailed pet information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'

components:
  schemas:
    Pets:
      type: object
      properties:
        objectsArrayWithAdditionalItems:
          type: array
          items:
            - type: object
              required:
                - id
                - name
              properties:
                id:
                  type: string
                name:
                  type: string
                additionalProperties: false
            - type: object
              required:
                - address
                - title
              properties:
                address:
                  type: string
                title:
                  type: string
                additionalProperties: false
          additionalItems: 
            type: object
            required:
              - status
              - ticket
            properties:
              status:
                type: string
              ticket:
                type: string
              additionalProperties: false
        additionalProperties: false
```
image
Note how status and ticket aren't included in a third array item.

**Comment by ilanashapiro** [comment]
@brendarearden Hi! Would it be possible to get a follow up review? Thank you!

**Review by brendarearden — APPROVED** [review]
looks good!

**Comment by brendarearden** [comment]
https://github.com/stoplightio/prism/issues/2519 I opened an issue to track the additionalitems bug you discovered as well!

**Pull request merged**
